IF OBJECT_ID (N'dbo.FC_CAU1', N'FN') IS NOT NULL
	DROP FUNCTION FC_CAU1;
GO 
CREATE FUNCTION dbo.FC_CAU1(@MAVT NVARCHAR(5))
RETURNS INT
AS
BEGIN
	DECLARE @GIAMUA INT
	SELECT @GIAMUA = GIAMUA FROM VATTU WHERE MAVT = @MAVT
	RETURN @GIAMUA;
END;
