IF OBJECT_ID (N'dbo.fc_CAU2', N'FN') IS NOT NULL
	DROP FUNCTION fc_CAU2;
GO
CREATE FUNCTION dbo.fc_CAU2(@MAKH NVARCHAR(30))
RETURNS NVARCHAR(30)
AS
BEGIN
	DECLARE @TENKH NVARCHAR(30);
	SELECT @TENKH = TENKH FROM KHACHHANG WHERE MAKH = @MAKH
	RETURN @TENKH;
END;