DROP TRIGGER SL_VATTU
GO
CREATE TRIGGER SL_VATTU ON VATTU AFTER INSERT AS
BEGIN
	UPDATE VATTU SET SLTON = SLTON -
	(SELECT SL FROM CHITIETHOADON WHERE MAVT = VATTU.MAVT)
	FROM VATTU
	INNER JOIN CHITIETHOADON ON CHITIETHOADON.MAVT = VATTU.MAVT
END
