
CREATE TRIGGER  CheckGiaBan ON CHITIETHOADON AFTER INSERT, UPDATE AS
BEGIN
	DECLARE @MAVT NVARCHAR(5), @GIABAN INT;
	SELECT @MAVT = CHITIETHOADON.MAVT, @GIABAN = CHITIETHOADON.GIABAN
	FROM VATTU
	INNER JOIN CHITIETHOADON ON VATTU.MAVT = CHITIETHOADON.MAVT
	WHERE VATTU.GIAMUA > CHITIETHOADON.GIABAN;
	PRINT N'Giá bán của 1 vật tư nhỏ hơn giá mua của sản phẩm đó bị xóa';
	DELETE FROM CHITIETHOADON WHERE GIABAN = @GIABAN AND MAVT = @MAVT;	
END