CREATE TRIGGER  CHECK_GIABAN ON VATTU AFTER UPDATE AS
BEGIN
	DECLARE @GIABAN INT, @GIAMUA INT
	SET @GIABAN = (SELECT GIABAN FROM VATTU INNER JOIN CHITIETHOADON ON
	CHITIETHOADON.MAVT = VATTU.MAVT)
	SET @GIAMUA = (SELECT GIAMUA FROM VATTU INNER JOIN CHITIETHOADON ON
	CHITIETHOADON.MAVT = VATTU.MAVT)
	IF @GIABAN < @GIAMUA
	SET @GIABAN = @GIAMUA
END