CREATE TABLE BIENTAPVIEN (
	MABT NVARCHAR(5) NOT NULL,
	TENBT NVARCHAR(30),
	DIACHI NVARCHAR(30),
	SDT NVARCHAR(10),
	NGAYSINH DATE,
	EMAIL NVARCHAR(30),
	CHUCDANH NVARCHAR(20),
	TIENLUONG INT,
	PRIMARY KEY (MAPT)
);