--Bảng BAIBAO và bảng PHONGVIEN có chung dữ liệu MAPV dùng INNER JOIN
--Bảng BAIBAO và bảng BIENTAPVIEN có chung dữ liệu MABT dùng INNER JOIN.
SELECT BAIBAO.MABB, PHONGVIEN.TENPV, BIENTAPVIEN.TENBT, BAIBAO.TENBB
FROM ((BAIBAO INNER JOIN PHONGVIEN ON BAIBAO.MAPV = PHONGVIEN.MAPV)
INNER JOIN BIENTAPVIEN ON BAIBAO.MABT = BIENTAPVIEN.MABT);