CREATE TABLE PHONGVIEN (
	MAPV NVARCHAR(5) NOT NULL,
	MAPT NVARCHAR(5) NOT NULL,
	TENPV NVARCHAR(30),
	DIACHI NVARCHAR(20),
	SDT NVARCHAR(10),
	NGAYSINH DATE,
	EMAIL NVARCHAR(30),
	TIENLUONG INT,
	PRIMARY KEY (MAPV),
	FOREIGN KEY (MAPT) REFERENCES BIENTAPVIEN (MAPT)
);