--Tìm số bài báo đã viết của mỗi phóng viên theo dữ liệu thực tế của bảng BAIBAO
CREATE PROCEDURE SLBaiBao
AS
BEGIN
	SELECT BAIBAO.MAPV, PHONGVIEN.TENPV, COUNT(BAIBAO.MABB) AS SLBaiBao
	FROM BAIBAO
	INNER JOIN PHONGVIEN ON BAIBAO.MAPV = PHONGVIEN.MAPV
	GROUP BY BAIBAO.MAPV, PHONGVIEN.TENPV, BAIBAO.MABB;
END
GO
