SELECT BAIBAO.MABB, BAIBAO.TENBB, PHONGVIEN.MAPV, PHONGVIEN.TENPV
FROM BAIBAO
INNER JOIN PHONGVIEN ON BAIBAO.MAPV = PHONGVIEN.MAPV
WHERE BAIBAO.CHUDE IN (SELECT CHUDE FROM BAIBAO WHERE CHUDE LIKE 'Covid-19%');