IF OBJECT_ID (N'dbo.fc_CAU4', N'FN') IS NOT NULL
	DROP FUNCTION fc_CAU4;
GO
CREATE FUNCTION dbo.fc_CAU4 (@MAVT NVARCHAR(5))
RETURNS NVARCHAR(5)
AS
BEGIN
	SELECT TOP 1 @MAVT = MAVT FROM CHITIETHOADON
	GROUP BY MAVT
	ORDER BY SUM(SL * GIABAN) DESC;
	RETURN @MAVT;
END;