SELECT MAVT FROM CHITIETHOADON WHERE MAHD = 'HD001';
DECLARE @MAHD NVARCHAR(5);
SET @MAHD = 'HD001';
SELECT MAVT FROM CHITIETHOADON WHERE MAHD LIKE '%' + @MAHD;
DECLARE @TONGTG INT;
SELECT MAVT,SL * GIABAN AS TONGTG FROM CHITIETHOADON WHERE MAVT
IN (SELECT MAVT FROM CHITIETHOADON WHERE MAHD LIKE '%' + @MAHD) AND 
MAHD = @MAHD;
SELECT TOP 1 SUM(SL * GIABAN) AS TONGGT, MAVT FROM CHITIETHOADON
	GROUP BY MAVT
	ORDER BY SUM(SL * GIABAN) DESC;
SELECT TOP 1 CHITIETHOADON.MAVT
	FROM CHITIETHOADON
	GROUP BY CHITIETHOADON.MAVT
	ORDER BY SUM(CHITIETHOADON.SL * CHITIETHOADON.GIABAN) DESC;
SELECT MAVT, TENVT FROM VATTU WHERE MAVT = (
	SELECT TOP 1 CHITIETHOADON.MAVT
	FROM CHITIETHOADON
	GROUP BY CHITIETHOADON.MAVT
	ORDER BY SUM(CHITIETHOADON.SL * CHITIETHOADON.GIABAN) DESC
);