DROP PROCEDURE sp_Cau5;
go
CREATE PROCEDURE sp_CAU5
AS
BEGIN
	SELECT MAVT, TENVT FROM VATTU WHERE MAVT = (
		SELECT TOP 1 CHITIETHOADON.MAVT
		FROM CHITIETHOADON
		GROUP BY CHITIETHOADON.MAVT
		ORDER BY SUM(CHITIETHOADON.SL * CHITIETHOADON.GIABAN) DESC
	)
END
GO
EXEC sp_CAU5;