CREATE PROCEDURE TinhTongDonHang @MAHD NVARCHAR(5)
AS 	
	UPDATE HOADON SET TONGTG = (SELECT DISTINCT SUM(SL * GIABAN) AS TONGTG
	FROM CHITIETHOADON
	WHERE MAHD = @MAHD
	GROUP BY CHITIETHOADON.MAHD) WHERE MAHD = @MAHD
GO




