DROP PROCEDURE sp_Cau5;
go
CREATE PROCEDURE sp_CAU5 (
	@MAVT NVARCHAR(5) OUTPUT,
	@TENVT NVARCHAR(30) OUTPUT
)
AS
BEGIN
	SELECT @MAVT = MAVT, @TENVT = TENVT FROM VATTU WHERE MAVT in (
		SELECT TOP 1 CHITIETHOADON.MAVT
		FROM CHITIETHOADON
		GROUP BY CHITIETHOADON.MAVT
		ORDER BY SUM(CHITIETHOADON.SL * CHITIETHOADON.GIABAN) DESC
	)
END
GO
