CREATE TRIGGER tg_CAU7 ON KHACHHANG AFTER INSERT
AS
BEGIN
	IF EXISTS (SELECT MAKH FROM KHACHHANG)
		RETURN;
	ELSE
		iNSERT INTO KHACHHANG VALUES ((SELECT TOP 1 MAKH FROM HOADON
		ORDER BY MAKH DESC), (SELECT TOP 1 MAKH FROM HOADON ORDER BY MAKH DESC),
		NULL, NULL, NULL);
END