DROP TRIGGER tg_CAU6;
GO
CREATE TRIGGER tg_CAU6 ON VATTU AFTER UPDATE AS
BEGIN
	DECLARE @GIAMUA INT, @MAVT NVARCHAR(5);
	SET @MAVT = 'VT01';
	IF EXISTS (SELECT MAVT FROM VATTU WHERE MAVT = @MAVT)
	SELECT @GIAMUA = GIAMUA FROM VATTU WHERE MAVT = @MAVT;
	INSERT INTO VATTU
	SELECT * FROM VATTU WHERE MAVT = @MAVT AND GIAMUA > @GIAMUA;
END