CREATE TABLE CHITIETHOADON (
	MAHD NVARCHAR(10) NOT NULL,
	MAVT NVARCHAR(5) NOT NULL,
	SL INT,
	KHUYENMAI INT,
	GIABAN INT,
	FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD),
	FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT),
	CHECK (SL > 0)
);