CREATE TABLE HOADON (
	MAHD NVARCHAR(10) NOT NULL,
	NGAY DATE check (NGAY >= GETDATE()),
	MAKH NVARCHAR(5) NOT NULL,
	TONGTG INT,
	PRIMARY KEY (MAHD),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
);