INSERT INTO KHACHHANG VALUES ('KH01', 'NGUYEN THI BE', 'TAN BINH', '08457895', 'bnt@yahoo.com');
INSERT INTO KHACHHANG VALUES ('KH02', 'LE HOANG NAM', 'BINH CHANH', '09878987', 'namlehoang@abc.com.vn');
INSERT INTO KHACHHANG VALUES ('KH03', 'TRAN THI CHIEU', 'TAN BINH', '08457895', '');
INSERT INTO KHACHHANG VALUES ('KH04', 'MAI THI QUE ANH', 'BINH CHANH', NULL, '');
INSERT INTO KHACHHANG VALUES ('KH05', 'LE VAN SANG', 'QUAN 10', NULL, 'sanglv@hcm.vnn.vn');
INSERT INTO KHACHHANG VALUES ('KH06', 'TRAN HOANG KHAI', 'TAN BINH', '08457897', '');