CREATE TABLE KHACHHANG (
	MAKH NVARCHAR(5) NOT NULL,
	TENKH NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(50),
	DT NVARCHAR(10),
	EMAIL NVARCHAR(30),
	CHECK (LEN(DT) >= 7 AND LEN(DT) <= 10),
	PRIMARY KEY (MAKH)
);