DROP PROCEDURE SP_CAU1
GO
CREATE PROCEDURE SP_CAU1 @MAHD NVARCHAR(10)
AS
BEGIN
	IF EXISTS (SELECT * FROM CHITIETHOADON WHERE MAHD = @MAHD)
	BEGIN
		DECLARE @TEMP INT
		SET @TEMP = (SELECT SL FROM CHITIETHOADON WHERE CHITIETHOADON.MAVT =
		'VT01' AND CHITIETHOADON.MAHD = @MAHD)
		* (SELECT GIABAN FROM CHITIETHOADON WHERE CHITIETHOADON.MAVT =
		'VT01'AND CHITIETHOADON.MAHD = @MAHD)
		+ (SELECT SL FROM CHITIETHOADON WHERE CHITIETHOADON.MAVT =
		'VT05' AND CHITIETHOADON.MAHD = @MAHD)
		* (SELECT GIABAN FROM CHITIETHOADON WHERE CHITIETHOADON.MAVT =
		'VT05'AND CHITIETHOADON.MAHD = @MAHD)
		UPDATE HOADON SET TONGTG = @TEMP
		WHERE MAHD = @MAHD;
	END
	
END
GO
EXEC SP_CAU1 @MAHD = 'HD001';