DROP PROCEDURE SP_CAU2
GO
CREATE PROCEDURE SP_CAU2 @DT NVARCHAR(10)
AS
BEGIN
	IF EXISTS (SELECT DT FROM KHACHHANG WHERE DT = @DT)
	PRINT 'CÓ SĐT KHÁCH HÀNG LÀ ' + @DT
	ELSE
	PRINT 'KHÔNG CÓ SĐT KHÁCH HÀNG LÀ ' + @DT
END
GO
EXEC SP_CAU2 @DT = '08457895';
EXEC SP_CAU2 @DT = '0386625869';