SELECT MAHD, NGAY, HOADON.MAKH, KHACHHANG.TENKH, KHACHHANG.DIACHI,
MIN (TONGTG) AS TONGGIATRI  FROM HOADON INNER JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
WHERE HOADON.NGAY LIKE '2000%'
GROUP BY MAHD, NGAY, HOADON.MAKH, KHACHHANG.TENKH, KHACHHANG.DIACHI;