SELECT CHITIETHOADON.MAHD, CHITIETHOADON.MAVT, VATTU.TENVT, CHITIETHOADON.GIABAN, VATTU.GIAMUA,
CHITIETHOADON.SL, VATTU.GIAMUA * CHITIETHOADON.SL AS TRIGIAMUA,
CHITIETHOADON.GIABAN * CHITIETHOADON.SL AS TRIGIABAN,
CHITIETHOADON.GIABAN * CHITIETHOADON.SL - VATTU.GIAMUA * CHITIETHOADON.SL AS TIENLOI
FROM VATTU INNER JOIN CHITIETHOADON ON VATTU.MAVT = CHITIETHOADON.MAVT;
