SELECT VATTU.MAVT, VATTU.TENVT, VATTU.DVT, VATTU.GIAMUA, VATTU.SLTON, CHITIETHOADON.GIABAN
FROM ((VATTU INNER JOIN CHITIETHOADON ON VATTU.MAVT = CHITIETHOADON.MAVT)
INNER JOIN HOADON ON CHITIETHOADON.MAHD = HOADON.MAHD)
WHERE HOADON.NGAY LIKE '2000%'
AND CHITIETHOADON.GIABAN IN (SELECT MAX(GIABAN) FROM CHITIETHOADON);