SELECT  vATTU.MAVT, VATTU.TENVT,VATTU.TENVT, SUM(SL) AS Tong_so_da_ban
FROM VATTU INNER JOIN CHITIETHOADON ON VATTU.MAVT = CHITIETHOADON.MAVT
GROUP BY VATTU.TENVT, VATTU.MAVT, VATTU.TENVT
ORDER BY MAVT;