SELECT TOP 1 KHACHHANG.MAKH, KHACHHANG.TENKH, KHACHHANG.DIACHI, KHACHHANG.DT, KHACHHANG.EMAIL,
CHITIETHOADON.SL
FROM ((HOADON RIGHT JOIN KHACHHANG
ON HOADON.MAKH = KHACHHANG.MAKH)
LEFT JOIN CHITIETHOADON ON HOADON.MAHD = CHITIETHOADON.MAHD)
ORDER BY SL;